language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"

install:
 - sudo apt-get update -qq 
 - sudo apt-get install python-dev xvfb
 - sudo apt-get install scrot libjpeg-dev zlib1g-dev xdotool eagle
 - wget --quiet --output-document=- http://launchpadlibrarian.net/19548160/povray_3.6.1-12_i386.deb | sudo dpkg --install - 
 - pip install -r requirements-test.txt
 - pip install .
 - pip install coveralls

script:  
 - xauth add :0 . `mcookie`
 - cd tests 
 - TESTS="easy test_scrot.py test_imagemagick.py"
 - nosetests -v --with-coverage --cover-package=eagexp
  
after_success:
 - coveralls
