language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"

install:
 - sudo apt-get update -qq 
 - sudo apt-get install python-dev xvfb
 - sudo apt-get install scrot libjpeg-dev zlib1g-dev xdotool eagle xserver-xephyr
 - sudo apt-get install libjpeg62 libtiff4
 - wget http://security.ubuntu.com/ubuntu/pool/multiverse/p/povray/povray_3.6.1-12_amd64.deb
 - sudo dpkg -i povray_3.6.1-12_amd64.deb 
 - pip install -r requirements-test.txt
 - pip install .
 - pip install coveralls

script:  
 - xauth add :0 . `mcookie`
 - cd tests 
 - nosetests -v --with-coverage --cover-package=eagexp
  
after_success:
 - coveralls


