language: python

matrix:
  include:
    - name: 3.6_xenial
      python: 3.6
      dist: xenial

    - name: 2.7_bionic
      python: 2.7
      dist: bionic

    - name: 3.6_bionic
      python: 3.6
      dist: bionic

    - name: 3.7_bionic
      python: 3.7
      dist: bionic

    - name: 3.8_bionic
      python: 3.8
      dist: bionic

    - name: 3.9_bionic
      python: 3.9
      dist: bionic
addons:
  apt:
    packages:
      - xvfb
      - xserver-xephyr
      - scrot
      - povray
      - povray-includes

before_install:
  - sudo dpkg --add-architecture i386
  - wget -O eagle.deb 'http://archive.ubuntu.com/ubuntu/pool/multiverse/e/eagle/eagle_6.6.0-2_i386.deb'
  - sudo apt-get install -y ./eagle.deb
  # - sudo apt-get install -y eagle:i386

install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then PYTHON=python; else PYTHON=python3; fi
  - $PYTHON -m pip install $PIPUSER --upgrade -r requirements-test.txt
  - $PYTHON -m pip install $PIPUSER --upgrade .
  - $PYTHON -m pip install -r requirements-test.txt
  - $PYTHON -m pip install --upgrade .

script:
  - cd tests
  - $PYTHON -m pytest -v .

