sudo: required
dist: trusty

language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"

install:
 - sudo apt-get update -qq 
 - sudo apt-get install python-dev xvfb
 - sudo apt-get install scrot libjpeg-dev zlib1g-dev xdotool eagle:i386 xserver-xephyr
 - sudo apt-get install libboost-thread-dev zlib1g-dev libpng12-dev libjpeg-turbo8-dev libtiff4-dev libopenexr-dev libsdl-gfx1.2-dev
 - pip install -r requirements-test.txt
 - pip install .
 - pip install coveralls
 - wget https://github.com/POV-Ray/povray/archive/3.7-stable.zip
 - unzip -qq 3.7-stable.zip
 - cd povray*
 - cd unix/
 - ./prebuild.sh
 - cd ../
 - ./configure COMPILED_BY="your name <email@address>" 
 - make --quiet
 - sudo make install
 - cd ../

script:  
 - xauth add :0 . `mcookie`
 - cd tests 
 - nosetests -v --with-coverage --cover-package=eagexp
  
after_success:
 - coveralls


